---
name: Windows

on:  # yamllint disable-line rule:trurhy
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:

jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: lukka/get-cmake@v3.28.3

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'c823fd3e57035b10d970a96da2796a2db55e5df5'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'win-x64-rel'
          buildPreset: 'win-x64-rel'
          testPreset: 'win-x64-rel'

      - name: Download soundfont
        run:
          aria2c -d build/win-x64-rel/CorsixTH/RelWithDebInfo https://github.com/Jacalz/fluid-soundfont/raw/master/SF3/FluidR3.sf3

      - name: Copy data files for archive
        run: |
          cp -R CorsixTH/Lua build/win-x64-rel/CorsixTH/RelWithDebInfo/Lua
          cp -R CorsixTH/Bitmap build/win-x64-rel/CorsixTH/RelWithDebInfo/Bitmap
          cp -R CorsixTH/Levels build/win-x64-rel/CorsixTH/RelWithDebInfo/Levels
          cp -R CorsixTH/Campaigns build/win-x64-rel/CorsixTH/RelWithDebInfo/Campaigns
          cp CorsixTH/CorsixTH.lua build/win-x64-rel/CorsixTH/RelWithDebInfo/

      - name: Archive Release
        uses: actions/upload-artifact@v3
        with:
          path: build/win-x64-rel/CorsixTH/RelWithDebInfo
          name: CorsixTH
